name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        mkdir install
        ./configure --prefix=${PWD}install --disable-x86asm
    - name: make
      run: make -j4
    - name: make check
      run: make check
    - name: make install
      run: make install
